coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

kart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
     path('', views.cart_detail, name='cart_detail'),
     path('add/<int:product_id>/', views.cart_add, name='cart_add'),
     path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
     path('register/', views.RegisterFormView.as_view(), name='register'),
     path('login/', views.LoginFormView.as_view(), name='login'),
     path('logout/', views.LogoutView.as_view(), name='logout'),
     path('', views.product_list, name='product_list'),
     path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
     path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

untitled/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('kart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kart/models.py
from django.db import models

# Create your models here.

kart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .form import CartAddProductForm
from coupons.forms import CouponApplyForm

@require_POST
def cart_add(request, product_id):
     cart = Cart(request)
     product = get_object_or_404(Product, id=product_id)
     form = CartAddProductForm(request.POST)
     if form.is_valid():
         cd = form.cleaned_data
         cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
     return redirect('cart:cart_detail')

def cart_remove(request, product_id):
     cart = Cart(request)
     product = get_object_or_404(Product, id=product_id)
     cart.remove(product)
     return redirect('cart:cart_detail')

def cart_detail(request):
     cart = Cart(request)
     for item in cart:
          item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
     coupon_apply_form = CouponApplyForm()
     return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

kart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Your shopping cart{% endblock %}
{% block content %}

     <h1>Корзина покупок</h1>
     <table class="cart">
         <thead>
             <tr>
                 <th>Фото</th>
                 <th>Товар</th>
                 <th>Количество</th>
                 <th>Удалить</th>
                 <th>Цена за единицу товара</th>
                 <th>Цена</th>
             </tr>
         </thead>
         <tbody>
             {% for item in cart %}
                 {% with product=item.product %}
                 <tr>
                     <td>
                         <a href="{{ product.get_absolute_url }}">
                         <img src="{% if product.image %}{{ product.image.url }}
                         {% else %}{% static "image/no_image.png" %}{% endif %}">
                         </a>
                     </td>
                     <td>{{ product.name }}</td>
                     <td>
                        <form action="{% url "cart:cart_add" product.id %}" method="post">
                             {{ item.update_quantity_form.quantity }}
                             {{ item.update_quantity_form.update }}
                             <input type="submit" value="Обновить">
                             {% csrf_token %}
                         </form>
                     </td>
                     <td><a href="{% url "cart:cart_remove" product.id%}">Удалить</a></td>
                     <td class="num">{{ item.price }}Тенге</td>
                     <td class="num">{{ item.total_price }} Тенге</td>
                 </tr>
                 {% endwith %}
             {% endfor %}
             {% if cart.coupon %}
                 <tr class="subtotal">
                     <td>Подсумма</td>
                     <td colspan="4"></td>
                     <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
                 </tr>
                 <tr>
                     <td>
                         "{{ cart.coupon.code }}" Купон
                         ({{ cart.coupon.discount }}% Скидка)
                     </td>
                     <td colspan="4"></td>
                     <td class="num neg">
                        - {{ cart.get_discount|floatformat:"2" }} Тенге
                     </td>
                 </tr>
                {% endif %}
                <tr class="total">
                     <td>Сумма</td>
                     <td colspan="4"></td>
                     <td class="num">
                        {{ cart.get_total_price_after_discount|floatformat:"2" }} Тенге
                 </td>
                </tr>
         </tbody>
     </table>
     <p>Использовать купон:</p>
        <form action="{% url "coupons:apply" %}" method="post">
         {{ coupon_apply_form }}
         <input type="submit" value="Применить">
         {% csrf_token %}
        </form>
     <p class="text-right">
         <a href="{% url "shop:product_list" %}" class="button light">Продолжить покупки</a>
         <a href="{% url "orders:order_create" %}" class="button">Оформить заказ</a>
     </p>

{% endblock %}