kart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
     path('', views.cart_detail, name='cart_detail'),
     path('add/<int:product_id>/', views.cart_add, name='cart_add'),
     path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
     path('register/', views.RegisterFormView.as_view(), name='register'),
     path('login/', views.LoginFormView.as_view(), name='login'),
     path('logout/', views.LogoutView.as_view(), name='logout'),
     path('', views.product_list, name='product_list'),
     path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
     path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

untitled/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('kart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
     name = models.CharField(max_length=200, db_index=True)
     slug = models.SlugField(max_length=200, unique=True)

     class Meta:
         ordering = ('name',)
         verbose_name = 'category'
         verbose_name_plural = 'categories'

     def __str__(self):
        return self.name

     def get_absolute_url(self):
            return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
     category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
     name = models.CharField(max_length=200, db_index=True)
     slug = models.SlugField(max_length=200, db_index=True)
     image = models.ImageField(upload_to='images', blank=True)
     description = models.TextField(blank=True)
     price = models.DecimalField(max_digits=10, decimal_places=2)
     available = models.BooleanField(default=True)
     created = models.DateTimeField(auto_now_add=True)
     updated = models.DateTimeField(auto_now=True)

     class Meta:
         ordering = ('name',)
         index_together = (('id', 'slug'),)

     def __str__(self):
        return self.name

     def get_absolute_url(self):
         return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from kart.form import CartAddProductForm
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.contrib.auth import logout

def product_list(request, category_slug=None):
     category = None
     categories = Category.objects.all()
     products = Product.objects.filter(available=True)
     if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
     products = products.filter(category=category)
     return render(request, 'shop/product/list.html',
         {'category': category,
         'categories': categories,
         'products': products})

def product_detail(request, id, slug):
     product = get_object_or_404(Product, id=id, slug=slug, available=True)
     cart_product_form = CartAddProductForm()
     return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/login"
    template_name = "shop/register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm

    template_name = "shop/login.html"


    success_url = "/"

    def form_valid(self, form):

        self.user = form.get_user()

        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")

shop/templates/shop/base.html
<!DOCTYPE html>
<html>
     <head>
         <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
         {% load static %}
         <title>{% block title %}My shop{% endblock %}</title>
         <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}" >
         <link href="{% static 'assets/css/font-awesome.min.css' %}" rel="stylesheet">
         <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
         <link href="{% static "css/base.css" %}" rel="stylesheet">
     </head>
     <body>
     <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><strong>Air soft</strong> Shop</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


                <ul class="nav navbar-nav navbar-right">
                    {%block login%}
                    {% if user.is_authenticated%}
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                          <a href="{% url 'shop:logout' %}"> Выйти </a>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                          <a>{{user.username}}</a>
                          <li>
                            <div class="basket-container">
                                {% with total_items=cart|length %}
                                    {% if cart|length > 0 %}
                                        <a href="{% url "cart:cart_detail" %}">Корзина:</a>
                                        <a href="{% url "cart:cart_detail" %}">
                                            {{ total_items }} шт.,
                                            {{ cart.get_total_price }} Тенге
                                        </a>
                                    {% else %}
                                        <a>Корзина пуста.</a>
                                    {% endif %}
                                {% endwith %}
                            <div class="basket-items hidden">
                                <ul class="">


                                </ul>
                            </div>
                            </div>

                        </li>
                    </ul>

                    {%else%}
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                          <a href="{% url 'shop:login' %}">Войти</a>
                        </li>
                        <li><a href="{% url 'shop:register' %}"> Зарегистрироваться </a> </li>

                    </ul>
                    {%endif%}
                    {%endblock%}


                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">24\7 Call-center <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><strong>Позвонить: </strong>+228 2832813 328183</a></li>
                            <li><a href="#"><strong>Написать: </strong>air-soft@mail.ru</a></li>
                            <li class="divider"></li>
                            <li><a href="#"><strong>Адресс: </strong>
                                <div>
                                    228, Алматы,<br />
                                        Казахстан
                                </div>
                            </a></li>
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </nav>


         <div id="content">


                    {% block content %}{% endblock %}


         </div>
     </body>
</html>

shop/templates/shop/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Air-soft store</title>
    <!-- Bootstrap core CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'ItemSlider/css/main-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
  <body>

    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><strong>Air soft</strong> Shop</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


                <ul class="nav navbar-nav navbar-right">
                    {%block login%}
                    {% if user.is_authenticated%}
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                          <a href="/logout"> Выйти </a>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                          <a>{{user.username}}</a>
                          <li><a href="#">Корзина</a></li>
                    </ul>

                    {%else%}
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                          <a href="/login">Войти</a>
                        </li>
                        <li><a href="/register"> Зарегистрироваться </a> </li>

                    </ul>
                    {%endif%}
                    {%endblock%}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">24\7 Call-center <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><strong>Позвонить: </strong>+228 2832813 328183</a></li>
                            <li><a href="#"><strong>Написать: </strong>air-soft@mail.ru</a></li>
                            <li class="divider"></li>
                            <li><a href="#"><strong>Адресс: </strong>
                                <div>
                                    228, Алматы,<br />
                                        Казахстан
                                </div>
                            </a></li>
                        </ul>
                    </li>
                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-9">



                </div>
                <br />

            </div>
            <!-- /.col -->


            <!-- /.col -->
        </div>

        <!-- /.row -->

<div class="col-md-322">
      <div class="container">
        <form action="" method="post">
          {% csrf_token %}
          <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
          {{ form.as_p }}
          <button type="submit">Войти</button>
        </form>
        </div>

    <!-- /.col -->
</div>
  </body>
</html>

shop/templates/shop/register.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Air-soft store</title>
    <!-- Bootstrap core CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'ItemSlider/css/main-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
  <body>

    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><strong>Air soft</strong> Shop</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


                <ul class="nav navbar-nav navbar-right">
                    {%block login%}
                    {% if user.is_authenticated%}
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                          <a href="/logout"> Выйти </a>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                          <a>{{user.username}}</a>
                          <li><a href="#">Корзина</a></li>
                    </ul>

                    {%else%}
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                          <a href="/login">Войти</a>
                        </li>
                        <li><a href="/register"> Зарегистрироваться </a> </li>

                    </ul>
                    {%endif%}
                    {%endblock%}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">24\7 Call-center <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><strong>Позвонить: </strong>+228 2832813 328183</a></li>
                            <li><a href="#"><strong>Написать: </strong>air-soft@mail.ru</a></li>
                            <li class="divider"></li>
                            <li><a href="#"><strong>Адресс: </strong>
                                <div>
                                    228, Алматы,<br />
                                        Казахстан
                                </div>
                            </a></li>
                        </ul>
                    </li>
                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

  <div class="container">
      <div class="col-md-4">
        <form action="" method="post">
          {% csrf_token %}
          <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
          {{ form.as_p }}
          <button type="submit">Зарегистрироваться</button>
        </form>
      </div>




</div>
  </body>

</html>